#!/usr/bin/env nextflow
_ids = ['SRR1514132', 'SRR1514133', 'SRR1514134', 'SRR1514135', 'SRR1514136', 'SRR1514137', 'SRR1514138', 'SRR1514139', 'SRR1514140', 'SRR1514141'].channel()
process Download_1M_Reads {
container 'inutano/sra-toolkit:latest'

input:
val id from _ids

output:
set file('*_1.fastq.gz'), file('*_2.fastq.gz') into _reads

shell:

    '''

fastq-dump -X 5 --split-files !{id}
gzip !{id}_*.fastq

    '''
}
workflow.onComplete {
println "Workflow execution summary"
println "---------------------------"
println "Workflow completed at: $workflow.complete"
println "Duration: ${workflow.duration}"
println "Execution status: ${ workflow.success ? 'OK' : 'failed' }"
if (!  workflow.success) {
println "Error message: $workflow.errorMessage"
}
println "Files generated by the execution are available in $workflow.workDir"
println "---------------------------"
}
